// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBACdtubkZfH3urk1BcPXwNhik8t78u19A',
    appId: '1:923035564460:web:9bf45ec403384ae6e8e209',
    messagingSenderId: '923035564460',
    projectId: 'route-movie-app-54819',
    authDomain: 'route-movie-app-54819.firebaseapp.com',
    storageBucket: 'route-movie-app-54819.firebasestorage.app',
    measurementId: 'G-FE2ST468ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmI7XCtuO9hIabeWT6R4NC8r-lFNdpXGU',
    appId: '1:923035564460:android:eade7f263d84520de8e209',
    messagingSenderId: '923035564460',
    projectId: 'route-movie-app-54819',
    storageBucket: 'route-movie-app-54819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxwA0-2nKTXe9il7HtaKXa9v9-KHdAaY',
    appId: '1:923035564460:ios:8d23ec8f4292922be8e209',
    messagingSenderId: '923035564460',
    projectId: 'route-movie-app-54819',
    storageBucket: 'route-movie-app-54819.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxwA0-2nKTXe9il7HtaKXa9v9-KHdAaY',
    appId: '1:923035564460:ios:8d23ec8f4292922be8e209',
    messagingSenderId: '923035564460',
    projectId: 'route-movie-app-54819',
    storageBucket: 'route-movie-app-54819.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBACdtubkZfH3urk1BcPXwNhik8t78u19A',
    appId: '1:923035564460:web:75b4834fe50d7304e8e209',
    messagingSenderId: '923035564460',
    projectId: 'route-movie-app-54819',
    authDomain: 'route-movie-app-54819.firebaseapp.com',
    storageBucket: 'route-movie-app-54819.firebasestorage.app',
    measurementId: 'G-X6LPBZL7SD',
  );
}
